"""create analytics db core tables

Revision ID: fa8b4a2bc6a5
Revises: e6a4f1c9b8d2
Create Date: 2026-06-12 02:54:25.013010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa8b4a2bc6a5'
down_revision: Union[str, Sequence[str], None] = 'e6a4f1c9b8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_source_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_types_code'), 'event_types', ['code'], unique=True)
    op.create_index(op.f('ix_event_types_id'), 'event_types', ['id'], unique=False)
    op.create_index(op.f('ix_event_types_is_active'), 'event_types', ['is_active'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('ingestion_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rows_loaded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_ingestion_type'), 'ingestion_runs', ['ingestion_type'], unique=False)
    op.create_index('ix_ingestion_runs_source_started_at', 'ingestion_runs', ['source_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('trading_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_code', sa.String(length=32), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('session_type', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_code', 'trading_date', name='uq_trading_calendar_market_code_trading_date')
    )
    op.create_index(op.f('ix_trading_calendar_id'), 'trading_calendar', ['id'], unique=False)
    op.create_index(op.f('ix_trading_calendar_is_trading_day'), 'trading_calendar', ['is_trading_day'], unique=False)
    op.create_index('ix_trading_calendar_market_date', 'trading_calendar', ['market_code', 'trading_date'], unique=False)
    op.create_index(op.f('ix_trading_calendar_trading_date'), 'trading_calendar', ['trading_date'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.String(length=128), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=64), nullable=True),
    sa.Column('importance', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type_id', 'event_date', 'title', name='uq_events_event_type_event_date_title')
    )
    op.create_index(op.f('ix_events_direction'), 'events', ['direction'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index('ix_events_event_type_event_date', 'events', ['event_type_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_source_event_id'), 'events', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_events_source_id'), 'events', ['source_id'], unique=False)
    op.create_index('ix_events_source_source_event_id', 'events', ['source_id', 'source_event_id'], unique=False)
    op.create_table('price_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'interval', 'begin_at', name='uq_price_candles_instrument_interval_begin_at')
    )
    op.create_index(op.f('ix_price_candles_begin_at'), 'price_candles', ['begin_at'], unique=False)
    op.create_index(op.f('ix_price_candles_id'), 'price_candles', ['id'], unique=False)
    op.create_index('ix_price_candles_instrument_interval_begin_at', 'price_candles', ['instrument_id', 'interval', 'begin_at'], unique=False)
    op.create_index('ix_price_candles_instrument_interval_trading_date', 'price_candles', ['instrument_id', 'interval', 'trading_date'], unique=False)
    op.create_index('ix_price_candles_interval_trading_date', 'price_candles', ['interval', 'trading_date'], unique=False)
    op.create_index(op.f('ix_price_candles_trading_date'), 'price_candles', ['trading_date'], unique=False)
    op.create_table('benchmark_constituents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benchmark_id', 'instrument_id', 'valid_from', name='uq_benchmark_constituents_benchmark_instrument_valid_from')
    )
    op.create_index(op.f('ix_benchmark_constituents_benchmark_id'), 'benchmark_constituents', ['benchmark_id'], unique=False)
    op.create_index('ix_benchmark_constituents_benchmark_valid_from', 'benchmark_constituents', ['benchmark_id', 'valid_from'], unique=False)
    op.create_index(op.f('ix_benchmark_constituents_id'), 'benchmark_constituents', ['id'], unique=False)
    op.create_index(op.f('ix_benchmark_constituents_instrument_id'), 'benchmark_constituents', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_benchmark_constituents_valid_from'), 'benchmark_constituents', ['valid_from'], unique=False)
    op.create_table('event_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_targets_benchmark_id'), 'event_targets', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_event_targets_event_id'), 'event_targets', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_targets_id'), 'event_targets', ['id'], unique=False)
    op.create_index(op.f('ix_event_targets_instrument_id'), 'event_targets', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_event_targets_issuer_id'), 'event_targets', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_event_targets_sector_id'), 'event_targets', ['sector_id'], unique=False)
    op.create_index(op.f('ix_event_targets_target_type'), 'event_targets', ['target_type'], unique=False)
    op.create_table('event_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'key', name='uq_event_values_event_id_key')
    )
    op.create_index(op.f('ix_event_values_event_id'), 'event_values', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_values_id'), 'event_values', ['id'], unique=False)
    op.create_index(op.f('ix_event_values_key'), 'event_values', ['key'], unique=False)
    op.create_table('study_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_type', sa.String(length=64), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_instrument_id', sa.Integer(), nullable=True),
    sa.Column('target_issuer_id', sa.Integer(), nullable=True),
    sa.Column('target_sector_id', sa.Integer(), nullable=True),
    sa.Column('market_benchmark_id', sa.Integer(), nullable=True),
    sa.Column('sector_benchmark_id', sa.Integer(), nullable=True),
    sa.Column('params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('methodology_version', sa.String(length=64), nullable=False),
    sa.Column('data_version', sa.String(length=128), nullable=True),
    sa.Column('data_cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['market_benchmark_id'], ['benchmarks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_benchmark_id'], ['benchmarks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_issuer_id'], ['issuers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_sector_id'], ['sectors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_runs_event_type_id'), 'study_runs', ['event_type_id'], unique=False)
    op.create_index(op.f('ix_study_runs_id'), 'study_runs', ['id'], unique=False)
    op.create_index(op.f('ix_study_runs_status'), 'study_runs', ['status'], unique=False)
    op.create_index('ix_study_runs_study_type_created_at', 'study_runs', ['study_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_study_runs_target_instrument_id'), 'study_runs', ['target_instrument_id'], unique=False)
    op.create_index(op.f('ix_study_runs_target_sector_id'), 'study_runs', ['target_sector_id'], unique=False)
    op.create_table('study_benchmark_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_run_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=False),
    sa.Column('horizon_trading_days', sa.Integer(), nullable=False),
    sa.Column('benchmark_method', sa.String(length=64), nullable=True),
    sa.Column('event_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('horizon_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('return_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('skipped_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_run_id'], ['study_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_run_id', 'event_id', 'benchmark_id', 'horizon_trading_days', name='uq_study_benchmark_results_run_event_benchmark_horizon')
    )
    op.create_index(op.f('ix_study_benchmark_results_benchmark_id'), 'study_benchmark_results', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_study_benchmark_results_event_id'), 'study_benchmark_results', ['event_id'], unique=False)
    op.create_index(op.f('ix_study_benchmark_results_id'), 'study_benchmark_results', ['id'], unique=False)
    op.create_index('ix_study_benchmark_results_run_horizon', 'study_benchmark_results', ['study_run_id', 'horizon_trading_days'], unique=False)
    op.create_index(op.f('ix_study_benchmark_results_status'), 'study_benchmark_results', ['status'], unique=False)
    op.create_table('study_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_run_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('comparison_type', sa.String(length=64), nullable=False),
    sa.Column('horizon_trading_days', sa.Integer(), nullable=False),
    sa.Column('instrument_return_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('benchmark_return_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('relative_return_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('skipped_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_run_id'], ['study_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_run_id', 'event_id', 'instrument_id', 'comparison_type', 'horizon_trading_days', name='uq_study_comparisons_run_event_instrument_type_horizon')
    )
    op.create_index(op.f('ix_study_comparisons_benchmark_id'), 'study_comparisons', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_study_comparisons_comparison_type'), 'study_comparisons', ['comparison_type'], unique=False)
    op.create_index(op.f('ix_study_comparisons_event_id'), 'study_comparisons', ['event_id'], unique=False)
    op.create_index(op.f('ix_study_comparisons_id'), 'study_comparisons', ['id'], unique=False)
    op.create_index(op.f('ix_study_comparisons_instrument_id'), 'study_comparisons', ['instrument_id'], unique=False)
    op.create_index('ix_study_comparisons_run_horizon', 'study_comparisons', ['study_run_id', 'horizon_trading_days'], unique=False)
    op.create_index(op.f('ix_study_comparisons_study_run_id'), 'study_comparisons', ['study_run_id'], unique=False)
    op.create_table('study_event_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_run_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('horizon_trading_days', sa.Integer(), nullable=False),
    sa.Column('event_candle_id', sa.Integer(), nullable=True),
    sa.Column('horizon_candle_id', sa.Integer(), nullable=True),
    sa.Column('event_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('horizon_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('return_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('skipped_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_candle_id'], ['price_candles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['horizon_candle_id'], ['price_candles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_run_id'], ['study_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_run_id', 'event_id', 'instrument_id', 'horizon_trading_days', name='uq_study_event_results_run_event_instrument_horizon')
    )
    op.create_index(op.f('ix_study_event_results_event_id'), 'study_event_results', ['event_id'], unique=False)
    op.create_index(op.f('ix_study_event_results_id'), 'study_event_results', ['id'], unique=False)
    op.create_index(op.f('ix_study_event_results_instrument_id'), 'study_event_results', ['instrument_id'], unique=False)
    op.create_index('ix_study_event_results_run_horizon', 'study_event_results', ['study_run_id', 'horizon_trading_days'], unique=False)
    op.create_index(op.f('ix_study_event_results_status'), 'study_event_results', ['status'], unique=False)
    op.create_table('study_horizon_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_run_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('horizon_trading_days', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('neutral_count', sa.Integer(), nullable=True),
    sa.Column('average_return_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('median_return_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('hit_rate_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('average_relative_return_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('median_relative_return_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('best_horizon_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_run_id'], ['study_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_horizon_summary_benchmark_id'), 'study_horizon_summary', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_study_horizon_summary_best_horizon_flag'), 'study_horizon_summary', ['best_horizon_flag'], unique=False)
    op.create_index(op.f('ix_study_horizon_summary_horizon_trading_days'), 'study_horizon_summary', ['horizon_trading_days'], unique=False)
    op.create_index(op.f('ix_study_horizon_summary_id'), 'study_horizon_summary', ['id'], unique=False)
    op.create_index(op.f('ix_study_horizon_summary_instrument_id'), 'study_horizon_summary', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_study_horizon_summary_sector_id'), 'study_horizon_summary', ['sector_id'], unique=False)
    op.create_index(op.f('ix_study_horizon_summary_study_run_id'), 'study_horizon_summary', ['study_run_id'], unique=False)
    op.create_index(op.f('ix_study_horizon_summary_subject_type'), 'study_horizon_summary', ['subject_type'], unique=False)
    op.create_table('study_run_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_run_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('skipped_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_run_id'], ['study_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_run_id', 'event_id', name='uq_study_run_events_study_run_event')
    )
    op.create_index(op.f('ix_study_run_events_event_id'), 'study_run_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_study_run_events_id'), 'study_run_events', ['id'], unique=False)
    op.create_index(op.f('ix_study_run_events_status'), 'study_run_events', ['status'], unique=False)
    op.create_index(op.f('ix_study_run_events_study_run_id'), 'study_run_events', ['study_run_id'], unique=False)
    op.create_table('study_skipped_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_run_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('context_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_run_id'], ['study_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_skipped_events_event_id'), 'study_skipped_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_study_skipped_events_id'), 'study_skipped_events', ['id'], unique=False)
    op.create_index(op.f('ix_study_skipped_events_reason_code'), 'study_skipped_events', ['reason_code'], unique=False)
    op.create_index(op.f('ix_study_skipped_events_study_run_id'), 'study_skipped_events', ['study_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_skipped_events_study_run_id'), table_name='study_skipped_events')
    op.drop_index(op.f('ix_study_skipped_events_reason_code'), table_name='study_skipped_events')
    op.drop_index(op.f('ix_study_skipped_events_id'), table_name='study_skipped_events')
    op.drop_index(op.f('ix_study_skipped_events_event_id'), table_name='study_skipped_events')
    op.drop_table('study_skipped_events')
    op.drop_index(op.f('ix_study_run_events_study_run_id'), table_name='study_run_events')
    op.drop_index(op.f('ix_study_run_events_status'), table_name='study_run_events')
    op.drop_index(op.f('ix_study_run_events_id'), table_name='study_run_events')
    op.drop_index(op.f('ix_study_run_events_event_id'), table_name='study_run_events')
    op.drop_table('study_run_events')
    op.drop_index(op.f('ix_study_horizon_summary_subject_type'), table_name='study_horizon_summary')
    op.drop_index(op.f('ix_study_horizon_summary_study_run_id'), table_name='study_horizon_summary')
    op.drop_index(op.f('ix_study_horizon_summary_sector_id'), table_name='study_horizon_summary')
    op.drop_index(op.f('ix_study_horizon_summary_instrument_id'), table_name='study_horizon_summary')
    op.drop_index(op.f('ix_study_horizon_summary_id'), table_name='study_horizon_summary')
    op.drop_index(op.f('ix_study_horizon_summary_horizon_trading_days'), table_name='study_horizon_summary')
    op.drop_index(op.f('ix_study_horizon_summary_best_horizon_flag'), table_name='study_horizon_summary')
    op.drop_index(op.f('ix_study_horizon_summary_benchmark_id'), table_name='study_horizon_summary')
    op.drop_table('study_horizon_summary')
    op.drop_index(op.f('ix_study_event_results_status'), table_name='study_event_results')
    op.drop_index('ix_study_event_results_run_horizon', table_name='study_event_results')
    op.drop_index(op.f('ix_study_event_results_instrument_id'), table_name='study_event_results')
    op.drop_index(op.f('ix_study_event_results_id'), table_name='study_event_results')
    op.drop_index(op.f('ix_study_event_results_event_id'), table_name='study_event_results')
    op.drop_table('study_event_results')
    op.drop_index(op.f('ix_study_comparisons_study_run_id'), table_name='study_comparisons')
    op.drop_index('ix_study_comparisons_run_horizon', table_name='study_comparisons')
    op.drop_index(op.f('ix_study_comparisons_instrument_id'), table_name='study_comparisons')
    op.drop_index(op.f('ix_study_comparisons_id'), table_name='study_comparisons')
    op.drop_index(op.f('ix_study_comparisons_event_id'), table_name='study_comparisons')
    op.drop_index(op.f('ix_study_comparisons_comparison_type'), table_name='study_comparisons')
    op.drop_index(op.f('ix_study_comparisons_benchmark_id'), table_name='study_comparisons')
    op.drop_table('study_comparisons')
    op.drop_index(op.f('ix_study_benchmark_results_status'), table_name='study_benchmark_results')
    op.drop_index('ix_study_benchmark_results_run_horizon', table_name='study_benchmark_results')
    op.drop_index(op.f('ix_study_benchmark_results_id'), table_name='study_benchmark_results')
    op.drop_index(op.f('ix_study_benchmark_results_event_id'), table_name='study_benchmark_results')
    op.drop_index(op.f('ix_study_benchmark_results_benchmark_id'), table_name='study_benchmark_results')
    op.drop_table('study_benchmark_results')
    op.drop_index(op.f('ix_study_runs_target_sector_id'), table_name='study_runs')
    op.drop_index(op.f('ix_study_runs_target_instrument_id'), table_name='study_runs')
    op.drop_index('ix_study_runs_study_type_created_at', table_name='study_runs')
    op.drop_index(op.f('ix_study_runs_status'), table_name='study_runs')
    op.drop_index(op.f('ix_study_runs_id'), table_name='study_runs')
    op.drop_index(op.f('ix_study_runs_event_type_id'), table_name='study_runs')
    op.drop_table('study_runs')
    op.drop_index(op.f('ix_event_values_key'), table_name='event_values')
    op.drop_index(op.f('ix_event_values_id'), table_name='event_values')
    op.drop_index(op.f('ix_event_values_event_id'), table_name='event_values')
    op.drop_table('event_values')
    op.drop_index(op.f('ix_event_targets_target_type'), table_name='event_targets')
    op.drop_index(op.f('ix_event_targets_sector_id'), table_name='event_targets')
    op.drop_index(op.f('ix_event_targets_issuer_id'), table_name='event_targets')
    op.drop_index(op.f('ix_event_targets_instrument_id'), table_name='event_targets')
    op.drop_index(op.f('ix_event_targets_id'), table_name='event_targets')
    op.drop_index(op.f('ix_event_targets_event_id'), table_name='event_targets')
    op.drop_index(op.f('ix_event_targets_benchmark_id'), table_name='event_targets')
    op.drop_table('event_targets')
    op.drop_index(op.f('ix_benchmark_constituents_valid_from'), table_name='benchmark_constituents')
    op.drop_index(op.f('ix_benchmark_constituents_instrument_id'), table_name='benchmark_constituents')
    op.drop_index(op.f('ix_benchmark_constituents_id'), table_name='benchmark_constituents')
    op.drop_index('ix_benchmark_constituents_benchmark_valid_from', table_name='benchmark_constituents')
    op.drop_index(op.f('ix_benchmark_constituents_benchmark_id'), table_name='benchmark_constituents')
    op.drop_table('benchmark_constituents')
    op.drop_index(op.f('ix_price_candles_trading_date'), table_name='price_candles')
    op.drop_index('ix_price_candles_interval_trading_date', table_name='price_candles')
    op.drop_index('ix_price_candles_instrument_interval_trading_date', table_name='price_candles')
    op.drop_index('ix_price_candles_instrument_interval_begin_at', table_name='price_candles')
    op.drop_index(op.f('ix_price_candles_id'), table_name='price_candles')
    op.drop_index(op.f('ix_price_candles_begin_at'), table_name='price_candles')
    op.drop_table('price_candles')
    op.drop_index('ix_events_source_source_event_id', table_name='events')
    op.drop_index(op.f('ix_events_source_id'), table_name='events')
    op.drop_index(op.f('ix_events_source_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index('ix_events_event_type_event_date', table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_direction'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_trading_calendar_trading_date'), table_name='trading_calendar')
    op.drop_index('ix_trading_calendar_market_date', table_name='trading_calendar')
    op.drop_index(op.f('ix_trading_calendar_is_trading_day'), table_name='trading_calendar')
    op.drop_index(op.f('ix_trading_calendar_id'), table_name='trading_calendar')
    op.drop_table('trading_calendar')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_source_started_at', table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_ingestion_type'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_event_types_is_active'), table_name='event_types')
    op.drop_index(op.f('ix_event_types_id'), table_name='event_types')
    op.drop_index(op.f('ix_event_types_code'), table_name='event_types')
    op.drop_table('event_types')
    # ### end Alembic commands ###
