export const MARKET_UNIVERSE = [
  { secid: "SBER", name: "Сбербанк", sector: "Banks", tags: ["liquid", "blue-chip"] },
  { secid: "SBERP", name: "Сбербанк прив.", sector: "Banks", tags: ["liquid"] },
  { secid: "VTBR", name: "ВТБ", sector: "Banks", tags: ["liquid"] },
  { secid: "T", name: "Т-Банк", sector: "Banks", tags: ["finance"] },
  { secid: "MOEX", name: "Московская биржа", sector: "Banks", tags: ["infrastructure"] },
  { secid: "CBOM", name: "МКБ", sector: "Banks", tags: ["finance"] },
  { secid: "GAZP", name: "Газпром", sector: "Oil & Gas", tags: ["liquid", "blue-chip"] },
  { secid: "LKOH", name: "Лукойл", sector: "Oil & Gas", tags: ["liquid", "blue-chip"] },
  { secid: "ROSN", name: "Роснефть", sector: "Oil & Gas", tags: ["blue-chip"] },
  { secid: "NVTK", name: "Новатэк", sector: "Oil & Gas", tags: ["blue-chip"] },
  { secid: "TATN", name: "Татнефть", sector: "Oil & Gas", tags: ["liquid"] },
  { secid: "TATNP", name: "Татнефть прив.", sector: "Oil & Gas", tags: ["liquid"] },
  { secid: "SNGS", name: "Сургутнефтегаз", sector: "Oil & Gas", tags: ["liquid"] },
  { secid: "SNGSP", name: "Сургутнефтегаз прив.", sector: "Oil & Gas", tags: ["liquid"] },
  { secid: "GMKN", name: "Норникель", sector: "Metals", tags: ["blue-chip"] },
  { secid: "NLMK", name: "НЛМК", sector: "Metals", tags: ["steel"] },
  { secid: "MAGN", name: "ММК", sector: "Metals", tags: ["steel"] },
  { secid: "CHMF", name: "Северсталь", sector: "Metals", tags: ["steel"] },
  { secid: "PLZL", name: "Полюс", sector: "Metals", tags: ["gold"] },
  { secid: "ALRS", name: "Алроса", sector: "Metals", tags: ["diamonds"] },
  { secid: "RUAL", name: "Русал", sector: "Metals", tags: ["aluminium"] },
  { secid: "YDEX", name: "Яндекс", sector: "Tech", tags: ["internet", "liquid"] },
  { secid: "VKCO", name: "VK", sector: "Tech", tags: ["internet"] },
  { secid: "POSI", name: "Positive Technologies", sector: "Tech", tags: ["software"] },
  { secid: "ASTR", name: "Группа Астра", sector: "Tech", tags: ["software"] },
  { secid: "MGNT", name: "Магнит", sector: "Retail", tags: ["consumer"] },
  { secid: "FIVE", name: "X5 Group", sector: "Retail", tags: ["consumer"] },
  { secid: "FIXP", name: "Fix Price", sector: "Retail", tags: ["consumer"] },
  { secid: "MTSS", name: "МТС", sector: "Telecom", tags: ["dividend"] },
  { secid: "RTKM", name: "Ростелеком", sector: "Telecom", tags: ["telecom"] },
  { secid: "HYDR", name: "РусГидро", sector: "Utilities", tags: ["power"] },
  { secid: "FEES", name: "Россети", sector: "Utilities", tags: ["grid"] },
  { secid: "IRAO", name: "Интер РАО", sector: "Utilities", tags: ["power"] },
  { secid: "PHOR", name: "ФосАгро", sector: "Chemicals", tags: ["fertilizers"] },
  { secid: "AKRN", name: "Акрон", sector: "Chemicals", tags: ["fertilizers"] },
  { secid: "AFLT", name: "Аэрофлот", sector: "Transport", tags: ["airline"] },
  { secid: "FLOT", name: "Совкомфлот", sector: "Transport", tags: ["shipping"] },
  { secid: "TRNFP", name: "Транснефть прив.", sector: "Transport", tags: ["infrastructure"] },
  { secid: "PIKK", name: "ПИК", sector: "Other", tags: ["real-estate"] },
  { secid: "AFKS", name: "АФК Система", sector: "Other", tags: ["holding"] },
];

export const MARKET_UNIVERSE_SECTORS = [
  "Banks",
  "Oil & Gas",
  "Metals",
  "Tech",
  "Retail",
  "Telecom",
  "Utilities",
  "Chemicals",
  "Transport",
  "Other",
];
